"""Public, broker-neutral strategy and plugin contracts."""

from .contracts import (
    CompositeAnalysisRequest,
    CompositeEvaluationRequest,
    CompositeMember,
    DiagnosticRecord,
    ParameterField,
    ParameterKind,
    ParameterNormalizationRequest,
    ParameterNormalizationResult,
    ParameterSchemaMetadata,
    ParameterTemplateRequest,
    ParameterTemplateResult,
    ParameterValidationResult,
    PluginArtifactIdentity,
    StrategyAnalysisResult,
    StrategyCapability,
    StrategyDescriptor,
    StrategyEvaluationRequest,
    StrategyEvaluationResult,
    StrategyIdentity,
    StrategyIntent,
    StrategyReference,
)
from .core import CompositeStrategy, Decision, MovingAverageCross, Strategy, StrategyRuntime
from .plugins import (
    StrategyCompositeAnalysisProvider,
    StrategyParameterNormalizationProvider,
    StrategyParameterTemplateProvider,
    StrategyPluginProvider,
)
from .registry import (
    StrategyCapabilityError,
    StrategyParameterError,
    StrategyPluginContractError,
    StrategyRegistry,
    StrategyRegistryError,
    UnknownPluginError,
    UnknownStrategyError,
)

__all__ = [
    "CompositeAnalysisRequest",
    "CompositeEvaluationRequest",
    "CompositeMember",
    "CompositeStrategy",
    "Decision",
    "DiagnosticRecord",
    "MovingAverageCross",
    "ParameterField",
    "ParameterKind",
    "ParameterNormalizationRequest",
    "ParameterNormalizationResult",
    "ParameterSchemaMetadata",
    "ParameterTemplateRequest",
    "ParameterTemplateResult",
    "ParameterValidationResult",
    "PluginArtifactIdentity",
    "Strategy",
    "StrategyAnalysisResult",
    "StrategyCapability",
    "StrategyCapabilityError",
    "StrategyCompositeAnalysisProvider",
    "StrategyDescriptor",
    "StrategyEvaluationRequest",
    "StrategyEvaluationResult",
    "StrategyIdentity",
    "StrategyIntent",
    "StrategyParameterNormalizationProvider",
    "StrategyParameterError",
    "StrategyParameterTemplateProvider",
    "StrategyPluginContractError",
    "StrategyPluginProvider",
    "StrategyReference",
    "StrategyRegistry",
    "StrategyRegistryError",
    "StrategyRuntime",
    "UnknownPluginError",
    "UnknownStrategyError",
]
